paths:
  fasta_dir: <inputPath>
  output_dir: <outputPath>
general:
  threads: 20
resources:
  mem_mb: 20000
  max_jobs: 2
bakta:
  enabled: true
  docker_image: engbio/bakta:v1
  db_path: <pathDatabase>/db-light
  db_type: light
  genus: Streptomyces
  species: Streptomyces
  strain: Streptomyces
  gram: '-'
  translation_table: 11
  min_contig_length: 100
  compliant: false
prokka:
  enabled: true
  docker_image: engbio/prokka:v1
  genus: Streptomyces
  kingdom: Bacteria
  gcode: 11
dfast:
  enabled: true
  docker_image: engbio/dfast:v1
  db_path: <pathDatabase>/dfast_db
  organism: unknown
patric:
  enabled: true
  docker_image: engbio/patric:v1
  username: username
  password: 'password'
  taxonomy_id: 1883
  description: Bacteria
  workspace_output_dir: home
  monitor_interval: 60
eggnog:
  enabled: true
  docker_image: engbio/eggnog:v2.1.15
  db_path: <pathDatabase>/eggnog_data
  sensmode: diamond
pgap:
  enabled: true
  script_path: pgap.py
  mem: 18g
  cpus: 18
  extra_args: --ignore-all-errors
  species: Streptomyces
merge:
  docker_image: engbio/merge:v1
  min_pident: 95
  min_qcov: 0.9
  jobs: 2
  #tool_order: bakta,prokka,dfast,pgap,eggnog
watchdog:
  max_retries: 4
  inactivity_timeout: 2880m
  check_interval: 240s
base_tool: patric
mode: genomic
